services:
  postgres:
    image: postgres:15
    container_name: sanare-postgres
    restart: always
    environment:
      POSTGRES_USER: sanare
      POSTGRES_PASSWORD: sanarepass
    ports:
      - '5432:5432'
    volumes:
      - sanare-postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sanare-net

  sanarebackend:
    build:
      context: ../api
    container_name: sanarebackend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sanare_app
      DB_USER: sanare
      DB_PASSWORD: sanarepass
      PORT: 3001
      NODE_ENV: development
    command: sh -c "npx sequelize-cli db:migrate && npm run start"
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - sanare-net

  sanarefrontend:
    build:
      context: ../..
      dockerfile: sanare-app/docker/Dockerfile.frontend
    container_name: sanarefrontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - '8081:80'
    networks:
      - sanare-net

networks:
  sanare-net:
    driver: bridge

volumes:
  sanare-postgres-data:
