services:
  postgres:
    image: postgres:15
    container_name: sanare-postgres
    restart: always
    environment:
      POSTGRES_USER: sanare
      POSTGRES_PASSWORD: sanarepass
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sanare-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: sanare-keycloak
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: sanare
      KC_DB_PASSWORD: sanarepass
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    networks:
      - sanare-net

  sanarebackend:
    build:
      context: ../api
    container_name: sanarebackend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sanare_app
      DB_USER: sanare
      DB_PASSWORD: sanarepass
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: sanare
      KEYCLOAK_CLIENT_ID: sanare-app
      KEYCLOAK_CLIENT_SECRET:
      PORT: 3001
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - keycloak
    networks:
      - sanare-net

  sanarefrontend:
    build:
      context: ../..
      dockerfile: sanare-app/docker/Dockerfile.frontend
    container_name: sanarefrontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - '8081:80'
    networks:
      - sanare-net

networks:
  sanare-net:
    driver: bridge
